config/routes.rb
Rails.application.routes.draw do

  root "truyens#index"
  

  get     "login"    => "sessions#new"
  post    "login"    => "sessions#create"
  delete  "logout"   => "sessions#destroy"
  resources :truyens do   resources :comments
  end
  resources :users
  resources :admins
  resources :danhmucs
  resources :truyens
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :truyen
end

app/models/danhmuc.rb
class Danhmuc < ApplicationRecord
end

app/models/status.rb
class Status < ApplicationRecord
  belongs_to :user
end

app/models/truyen.rb
class Truyen < ApplicationRecord
    def self.search(term)
   

        if term
          where('tentruyen LIKE ?', "%#{term}%")
        else
          all
        end
      end
      has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :comments
    
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  before_action :set_admin, only: %i[ show edit update destroy ]

  # GET /admins or /admins.json
  def index
    @admins = Admin.all
   @adminscount1 =  Truyen.all.count
   @danhmuccount = Danhmuc.all.count
   @usercount = User.all.count
   @commentcount = Comment.all.count
  end

  # GET /admins/1 or /admins/1.json
  def show
  end

  # GET /admins/new
  def new
    @admin = Admin.new
    @truyen = Truyen.all
    @danhmuc = Danhmuc.all

  end

  # GET /admins/1/edit
  def edit
  end

  # POST /admins or /admins.json
  def create
    @admin = Admin.new(admin_params)

    respond_to do |format|
      if @admin.save
        format.html { redirect_to @admin, notice: "Admin was successfully created." }
        format.json { render :show, status: :created, location: @admin }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @admin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admins/1 or /admins/1.json
  def update
    respond_to do |format|
      if @admin.update(admin_params)
        format.html { redirect_to admin_path, notice: "Admin was successfully updated." }
         format.json { head :no_content }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @admin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admins/1 or /admins/1.json
  def destroy
    @admin.destroy
    respond_to do |format|
      format.html { redirect_to admin_path, notice: "Admin was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin
      @admin = Admin.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def admin_params
      params.require(:admin).permit(:name)
    end
end

app/controllers/truyens_controller.rb
class TruyensController < ApplicationController
  before_action :set_truyen, only: %i[ show edit update destroy ]

  # GET /truyens or /truyens.json
  def index
    @truyens = Truyen.all
    @danhmucs = Danhmuc.all
    @users = User.all
    @truyens = Truyen.search(params[:term])
    @truyens2 = Truyen.where(iddanhmuc:2)
    @truyens1 = Truyen.where(iddanhmuc:1)   
    @user = User.find_by id: params[:id]
    
  end

  # GET /truyens/1 or /truyens/1.json
  def show
    
    @users = User.all
    @truyens = Truyen.all
    @danhmucs = Danhmuc.all
    @truyens = Truyen.search(params[:term])
   

   

  end

  # GET /truyens/new
  def new
    @truyen = Truyen.new
    

  end

  # GET /truyens/1/edit
  def edit
  end
  def truyen_params
    params.require(:truyen).permit(:term)
  end

  # POST /truyens or /truyens.json
  def create
    @truyen = Truyen.new(truyen_params)
   
    
    
    respond_to do |format|
      if @truyen.save
        format.html { redirect_to truyens_path, notice: "Truyen was successfully updated." }
        format.json { head :no_content }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @truyen.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /truyens/1 or /truyens/1.json
  def update
    respond_to do |format|
      if @truyen.update(truyen_params)
        format.html { redirect_to admins_path }
        format.json { head :no_content }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @truyen.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /truyens/1 or /truyens/1.json
  def destroy
    @truyen.destroy
    respond_to do |format|
      format.html { redirect_to truyens_path, notice: "Truyen was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_truyen
      @truyen = Truyen.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def truyen_params
      params.require(:truyen).permit(:tentruyen, :mota, :noidung, :iddanhmuc, :thoiluong, :anh)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
 
  
  def index
  end

  def new
    @user = User.new
    
  end
  def show
 
    @user = User.find_by id: params[:id]
   
  end
  def create
    @user = User.new user_params
    if @user.save
      flash[:success] = "Register success"
      redirect_to truyens_path
    else
      flash[:success] = "Register failed"
      render :new
    end
  end
  
  private
  def user_params
    params.require(:user).permit :name, :password, :password_confirmation
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/danhmucs_helper.rb
module DanhmucsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in user
        session[:user_id] = user.id
      end
      def log_out
        session.delete :user_id
      end
end

app/helpers/status_comments_helper.rb
module StatusCommentsHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/helpers/truyens_helper.rb
module TruyensHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/_form.html.erb
<%= form_with(model: admin) do |form| %>
  <% if admin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(admin.errors.count, "error") %> prohibited this admin from being saved:</h2>

      <ul>
        <% admin.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admins/edit.html.erb
<h1>Editing Admin</h1>

<%= render 'form', admin: @admin %>

<%= link_to 'Show', @admin %> |
<%= link_to 'Back', admins_path %>

app/views/admins/index.html.erb
<!DOCTYPE html>

<html lang="en">
<head>
<base href="./">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
<meta name="description" content="CoreUI - Open Source Bootstrap Admin Template">
<meta name="author" content="Łukasz Holeczek">
<meta name="keyword" content="Bootstrap,Admin,Template,Open,Source,jQuery,CSS,HTML,RWD,Dashboard">
<title>CoreUI Free Bootstrap Admin Template</title>

<link rel="manifest" href="assets/favicon/manifest.json">
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="msapplication-TileImage" content="assets/favicon/ms-icon-144x144.png">
<meta name="theme-color" content="#ffffff">

<link href="css/style.css" rel="stylesheet">

<link href="vendors/@coreui/chartjs/css/coreui-chartjs.css" rel="stylesheet">
<meta name="robots" content="noindex">
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-118965717-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'UA-118965717-1');
</script></head>
<body class="c-app">
<div class="c-sidebar c-sidebar-dark c-sidebar-fixed c-sidebar-lg-show" id="sidebar">
<div class="c-sidebar-brand d-lg-down-none">
<svg class="c-sidebar-brand-full" width="118" height="46" alt="CoreUI Logo">
<use xlink:href="assets/brand/coreui.svg#full"></use>
</svg>
<svg class="c-sidebar-brand-minimized" width="46" height="46" alt="CoreUI Logo">
<use xlink:href="assets/brand/coreui.svg#signet"></use>
</svg>
</div>
<ul class="c-sidebar-nav">
<li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="truyens/">
<svg class="c-sidebar-nav-icon">
<use xlink:href="vendors/@coreui/icons/svg/free.svg#cil-speedometer"></use>
</svg>Trang Chủ<span class="badge badge-info">NEW</span></a></li>
<li class="c-sidebar-nav-title">Theme</li>
<li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="/truyens/new">
<svg class="c-sidebar-nav-icon">
<use xlink:href="vendors/@coreui/icons/svg/free.svg#cil-drop"></use>
</svg>Thêm Truyện</a></li>
<li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="/danhmucs/new">
<svg class="c-sidebar-nav-icon">
<use xlink:href="vendors/@coreui/icons/svg/free.svg#cil-pencil"></use>
</svg>Thêm Danh Mục</a></li>
<li class="c-sidebar-nav-title">List</li>
<li class="c-sidebar-nav-item c-sidebar-nav-dropdown"><a class="c-sidebar-nav-link c-sidebar-nav-dropdown-toggle" href="admins/new">
<svg class="c-sidebar-nav-icon">
<use xlink:href="vendors/@coreui/icons/svg/free.svg#cil-puzzle"></use>
</svg>Danh sách truyện</a></li>
<li class="c-sidebar-nav-item c-sidebar-nav-dropdown"><a class="c-sidebar-nav-link c-sidebar-nav-dropdown-toggle" href="admins/new">
<svg class="c-sidebar-nav-icon">
<use xlink:href="vendors/@coreui/icons/svg/free.svg#cil-puzzle"></use>
</svg>Danh sách danh mục</a></li>





</ul>
<button class="c-sidebar-minimizer c-class-toggler" type="button" data-target="_parent" data-class="c-sidebar-minimized"></button>
</div>
<div class="c-wrapper c-fixed-components">
<header class="c-header c-header-light c-header-fixed c-header-with-subheader">
<button class="c-header-toggler c-class-toggler d-lg-none mfe-auto" type="button" data-target="#sidebar" data-class="c-sidebar-show">
<svg class="c-icon c-icon-lg">
<use xlink:href="vendors/@coreui/icons/svg/free.svg#cil-menu"></use>
</svg>
</button><a class="c-header-brand d-lg-none" href="#">
<svg width="118" height="46" alt="CoreUI Logo">
<use xlink:href="assets/brand/coreui.svg#full"></use>
</svg></a>
<button class="c-header-toggler c-class-toggler mfs-3 d-md-down-none" type="button" data-target="#sidebar" data-class="c-sidebar-lg-show" responsive="true">
<svg class="c-icon c-icon-lg">
<use xlink:href="vendors/@coreui/icons/svg/free.svg#cil-menu"></use>
</svg>
</button>
<ul class="c-header-nav d-md-down-none">
<li class="c-header-nav-item px-3"><a class="c-header-nav-link" href="#">Dashboard</a></li>
<li class="c-header-nav-item px-3"><a class="c-header-nav-link" href="#">Users</a></li>
<li class="c-header-nav-item px-3"><a class="c-header-nav-link" href="#">Settings</a></li>
</ul>

<div class="c-subheader px-3">

<ol class="breadcrumb border-0 m-0">
<li class="breadcrumb-item">Home</li>
<li class="breadcrumb-item"><a href="#">Admin</a></li>
<li class="breadcrumb-item active">Dashboard</li>

</ol>
</div>
</header>
<div class="c-body">
<main class="c-main">
<div class="container-fluid">
<div class="fade-in">
<div class="row">
<div class="col-sm-6 col-lg-3">
<div class="card text-white bg-primary">
<div class="card-body card-body pb-0 d-flex justify-content-between align-items-start">
<div>
<div class="text-value-lg"> <%= @danhmuccount  %></div>
<div>Danh Mục Hiện Có</div>
</div>
<div class="btn-group">
<button class="btn btn-transparent dropdown-toggle p-0" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
<svg class="c-icon">
<use xlink:href="vendors/@coreui/icons/svg/free.svg#cil-settings"></use>
</svg>
</button>
<div class="dropdown-menu dropdown-menu-right"><a class="dropdown-item" href="#">Action</a><a class="dropdown-item" href="#">Another action</a><a class="dropdown-item" href="#">Something else here</a></div>
</div>
</div>
<div class="c-chart-wrapper mt-3 mx-3" style="height:70px;">
<canvas class="chart" id="card-chart1" height="70"></canvas>
</div>
</div>
</div>

<div class="col-sm-6 col-lg-3">
<div class="card text-white bg-info">
<div class="card-body card-body pb-0 d-flex justify-content-between align-items-start">
<div>
<div class="text-value-lg"> <%= @usercount  %></div>
<div>Người Dùng Hiện Có</div>
</div>
<div class="btn-group">
<button class="btn btn-transparent dropdown-toggle p-0" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
<svg class="c-icon">
<use xlink:href="vendors/@coreui/icons/svg/free.svg#cil-settings"></use>
</svg>
</button>
<div class="dropdown-menu dropdown-menu-right"><a class="dropdown-item" href="#">Action</a><a class="dropdown-item" href="#">Another action</a><a class="dropdown-item" href="#">Something else here</a></div>
</div>
</div>
<div class="c-chart-wrapper mt-3 mx-3" style="height:70px;">
<canvas class="chart" id="card-chart2" height="70"></canvas>
</div>
</div>
</div>

<div class="col-sm-6 col-lg-3">
<div class="card text-white bg-warning">
<div class="card-body card-body pb-0 d-flex justify-content-between align-items-start">
<div>
<div class="text-value-lg">

  <%= @adminscount1  %>
</div>
<div>Truyện Hiện Có</div>
</div>
<div class="btn-group">
<button class="btn btn-transparent dropdown-toggle p-0" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
<svg class="c-icon">
<use xlink:href="vendors/@coreui/icons/svg/free.svg#cil-settings"></use>
</svg>
</button>
<div class="dropdown-menu dropdown-menu-right"><a class="dropdown-item" href="#">Action</a><a class="dropdown-item" href="#">Another action</a><a class="dropdown-item" href="#">Something else here</a></div>
</div>
</div>
<div class="c-chart-wrapper mt-3" style="height:70px;">
<canvas class="chart" id="card-chart3" height="70"></canvas>
</div>
</div>
</div>

<div class="col-sm-6 col-lg-3">
<div class="card text-white bg-danger">
<div class="card-body card-body pb-0 d-flex justify-content-between align-items-start">
<div>
<div class="text-value-lg"> <%= @commentcount  %></div>
<div>Comment Hiện Có</div>
</div>
<div class="btn-group">
<button class="btn btn-transparent dropdown-toggle p-0" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
<svg class="c-icon">
<use xlink:href="vendors/@coreui/icons/svg/free.svg#cil-settings"></use>
</svg>
</button>
<div class="dropdown-menu dropdown-menu-right"><a class="dropdown-item" href="#">Action</a><a class="dropdown-item" href="#">Another action</a><a class="dropdown-item" href="#">Something else here</a></div>
</div>
</div>
<div class="c-chart-wrapper mt-3 mx-3" style="height:70px;">
<canvas class="chart" id="card-chart4" height="70"></canvas>
</div>
</div>
</div>

</div>

<div class="card">
<div class="card-body">
<div class="d-flex justify-content-between">
<div>
<h4 class="card-title mb-0">Traffic</h4>
<div class="small text-muted">September 2019</div>
</div>
<div class="btn-toolbar d-none d-md-block" role="toolbar" aria-label="Toolbar with buttons">
<div class="btn-group btn-group-toggle mx-3" data-toggle="buttons">
<label class="btn btn-outline-secondary">
<input id="option1" type="radio" name="options" autocomplete="off"> Day
</label>
<label class="btn btn-outline-secondary active">
<input id="option2" type="radio" name="options" autocomplete="off" checked=""> Month
</label>
<label class="btn btn-outline-secondary">
<input id="option3" type="radio" name="options" autocomplete="off"> Year
</label>
</div>
<button class="btn btn-primary" type="button">
<svg class="c-icon">
<use xlink:href="vendors/@coreui/icons/svg/free.svg#cil-cloud-download"></use>
</svg>
</button>
</div>
</div>
<div class="c-chart-wrapper" style="height:300px;margin-top:40px;">
<canvas class="chart" id="main-chart" height="300"></canvas>
</div>
</div>
<div class="card-footer">
<div class="row text-center">
<div class="col-sm-12 col-md mb-sm-2 mb-0">
<div class="text-muted">Visits</div><strong>29.703 Users (40%)</strong>
<div class="progress progress-xs mt-2">
<div class="progress-bar bg-success" role="progressbar" style="width: 40%" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100"></div>
</div>
</div>
<div class="col-sm-12 col-md mb-sm-2 mb-0">
<div class="text-muted">Unique</div><strong>24.093 Users (20%)</strong>
<div class="progress progress-xs mt-2">
<div class="progress-bar bg-info" role="progressbar" style="width: 20%" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100"></div>
</div>
</div>
<div class="col-sm-12 col-md mb-sm-2 mb-0">
<div class="text-muted">Pageviews</div><strong>78.706 Views (60%)</strong>
<div class="progress progress-xs mt-2">
<div class="progress-bar bg-warning" role="progressbar" style="width: 60%" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100"></div>
</div>
</div>
<div class="col-sm-12 col-md mb-sm-2 mb-0">
<div class="text-muted">New Users</div><strong>22.123 Users (80%)</strong>
<div class="progress progress-xs mt-2">
<div class="progress-bar bg-danger" role="progressbar" style="width: 80%" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100"></div>
</div>
</div>
<div class="col-sm-12 col-md mb-sm-2 mb-0">
<div class="text-muted">Bounce Rate</div><strong>40.15%</strong>
<div class="progress progress-xs mt-2">
<div class="progress-bar" role="progressbar" style="width: 40%" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100"></div>
</div>
</div>
</div>
</div>
</div>



</div>

</div>
</div>
</main>
<footer class="c-footer">
<div><a href="https://coreui.io">CoreUI</a> © 2020 creativeLabs.</div>
<div class="ml-auto">Powered by&nbsp;<a href="https://coreui.io/">CoreUI</a></div>
</footer>
</div>
</div>

<script src="vendors/@coreui/coreui/js/coreui.bundle.min.js"></script>
<!--[if IE]><!-->
<script src="vendors/@coreui/icons/js/svgxuse.min.js"></script>
<!--<![endif]-->

<script src="vendors/@coreui/chartjs/js/coreui-chartjs.bundle.js"></script>
<script src="vendors/@coreui/utils/js/coreui-utils.js"></script>
<script src="js/main.js"></script>
</body>
</html>

app/views/admins/new.html.erb
<p id="notice"><%= notice %></p>



<h1 style="text-align:center">DANH SÁCH TRUYỆN</h1>
<table class="table table-striped">
    <thead>
      <tr>      
        <th>TÊN TRUYỆN</th>
        <th>MÔ TẢ</th>
        <th>NỘI DUNG</th>
        <th>THỜI LƯỢNG</th>
        <th></th>
        <th></th>


      </tr>
    </thead>
    <tbody>
    <% @truyen.each do |truyen| %>
      <tr>
       
        <td><%= truyen.tentruyen %></td>
         <td><%= truyen.mota %></td>
         <td><%= truyen.noidung %></td>
         
         <td><%= truyen.thoiluong %></td>


        <td><button type="button" class="btn btn-success" ><%= link_to 'Edit', edit_truyen_path(truyen) %></button></td>
        <td><button type="button" class="btn btn-success"><%= link_to 'Destroy', truyen, method: :delete, data: { confirm: 'Are you sure?' } %></button></td>
      </tr>
      <% end %>
     
    </tbody>
  </table>




  

<p id="notice"><%= notice %></p>



<h1 style="text-align:center">DANH SÁCH DANH MỤC</h1>
<table class="table table-striped">
    <thead>
    
      <tr>      
        <th>ID</th>
        <th>Tên Danh Mục</th>
      </tr>
    </thead>
    <tbody>
<% @danhmuc.each do |danhmuc| %>
      <tr>
      <td><%= danhmuc.id %></td>
      <td><%= danhmuc.tendanhmuc %></td>
     <td><button type="button" class="btn btn-success" ><%= link_to 'Edit', edit_danhmuc_path(danhmuc) %></button></td>
     <td><button type="button" class="btn btn-success"><%= link_to 'Destroy', danhmuc, method: :delete, data: { confirm: 'Are you sure?' } %></button></td>
      </tr>
      <% end %>
     
    </tbody>
  </table>

app/views/admins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @admin.name %>
</p>

<%= link_to 'Edit', edit_admin_path(@admin) %> |
<%= link_to 'Back', admins_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <section class="content" style="min-height: auto;">
  <% flash.each do |key, value| %>
    <div class="row">
      <div class="alert alert-<%= key %>">
        <%= value %>
      </div>
    </div>
  <% end %>
</section>
<%= yield %>

  </body>
</html>