config/routes.rb
Rails.application.routes.draw do

  root "truyens#index"
  

  get     "login"    => "sessions#new"
  post    "login"    => "sessions#create"
  delete  "logout"   => "sessions#destroy"
  resources :truyens do   resources :comments
  end
  resources :users
  resources :admins
  resources :danhmucs
  resources :truyens
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :comments
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
 
  
  def index
  end

  def new
    @user = User.new
    
  end
  def show
 
    @user = User.find_by id: params[:id]
   
  end
  def create
    @user = User.new user_params
    if @user.save
      flash[:success] = "Register success"
      redirect_to truyens_path
    else
      flash[:success] = "Register failed"
      render :new
    end
  end
  
  private
  def user_params
    params.require(:user).permit :name, :password, :password_confirmation
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
# <%= form_with(model: user) do |form| %>
#   <% if user.errors.any? %>
#     <div id="error_explanation">
#       <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

#       <ul>
#         <% user.errors.each do |error| %>
#           <li><%= error.full_message %></li>
#         <% end %>
#       </ul>
#     </div>
#   <% end %>

#   <div class="field">
#     <%= form.label :name %>
#     <%= form.text_field :name %>
#   </div>

#   <div class="field">
#     <%= form.label :password_digest %>
#     <%= form.text_field :password_digest %>
#   </div>

#   <div class="actions">
#     <%= form.submit %>
#   </div>
# <% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Password digest</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.password_digest %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/users/new.html.erb
<div class="login-wrap">
	<div class="login-html">
		<input id="tab-1" type="radio" name="tab" class="sign-in" checked><label for="tab-1" class="tab">Sign In</label>
		<input id="tab-2" type="radio" name="tab" class="sign-up"><label for="tab-2" class="tab">Sign Up</label>
		<div class="login-form">
			<div class="sign-in-htm">
    <%= form_for @user, html: {class: "form-horizontal"} do |f| %>

				<div class="group">
        <%= f.label :name, "Username", class: "label" %>
        <%= f.text_field :name, class: "input", placeholder: "Enter user name" %>								
				</div>
				<div class="group">
					
        <%= f.label :password, "Password", class: "label" %>
        <%= f.password_field :password, class: "input", placeholder: "Enter password" %>

				</div>
				<div class="group">
        <%= f.label :password_confirmation, "Password Confirmation", class: "label" %>
        <%= f.password_field :password_confirmation, class: "input", placeholder: "Enter password confirmation" %>
				</div>
				<div class="group">
        <%= f.submit "Register", class: "button" %>
				</div>
        <% end %>



				<div class="hr"></div>
				<div class="foot-lnk">
					<a href="#forgot">Forgot Password?</a>
				</div>
			</div>
			<div class="sign-up-htm">
				<div class="group">
					<label for="user" class="label">Username</label>
					<input id="user" type="text" class="input">
				</div>
				<div class="group">
					<label for="pass" class="label">Password</label>
					<input id="pass" type="password" class="input" data-type="password">
				</div>
				<div class="group">
					<label for="pass" class="label">Repeat Password</label>
					<input id="pass" type="password" class="input" data-type="password">
				</div>
				<div class="group">
					<label for="pass" class="label">Email Address</label>
					<input id="pass" type="text" class="input">
				</div>
				<div class="group">
					<input type="submit" class="button" value="Sign Up">
				</div>
     
				<div class="hr"></div>
				<div class="foot-lnk">
					<label for="tab-1">Already Member?</a>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<style>
.full {
  background-image: url("/assets/bgm.jpg");
.form-control{
    color:white;
    width:500px;
}
}
</style>
<div class = "full" style="max-width:100%;height:800px;">
 <h1 style = "color:white;text-align:center">CẬP NHẬT TRUYỆN</h1>
 <div style="margin-left:450px;">
 
 <label><%= @user.name %></label>
    
      <%= link_to "Logout", logout_path, method: :delete %> 

 </div>
 
</div>
  
  