config/routes.rb
Rails.application.routes.draw do

  root "truyens#index"
  

  get     "login"    => "sessions#new"
  post    "login"    => "sessions#create"
  delete  "logout"   => "sessions#destroy"
  resources :truyens do   resources :comments
  end
  resources :users
  resources :admins
  resources :danhmucs
  resources :truyens
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/danhmuc.rb
class Danhmuc < ApplicationRecord
end

app/controllers/danhmucs_controller.rb
class DanhmucsController < ApplicationController
  before_action :set_danhmuc, only: %i[ show edit update destroy ]

  # GET /danhmucs or /danhmucs.json
  def index
    @danhmucs = Danhmuc.all
  end

  # GET /danhmucs/1 or /danhmucs/1.json
  def show
  end

  # GET /danhmucs/new
  def new
    @danhmuc = Danhmuc.new
  end

  # GET /danhmucs/1/edit
  def edit
  end

  # POST /danhmucs or /danhmucs.json
  def create
    @danhmuc = Danhmuc.new(danhmuc_params)

    respond_to do |format|
      if @danhmuc.save
        format.html {redirect_to @danhmuc, notice: "Danhmuc was successfully created." }
        format.json { render :show, status: :created, location: @danhmuc }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @danhmuc.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /danhmucs/1 or /danhmucs/1.json
  def update
    respond_to do |format|
      if @danhmuc.update(danhmuc_params)
        format.html { redirect_to admins_path, notice: "" }
        format.json { head :no_content }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @danhmuc.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /danhmucs/1 or /danhmucs/1.json
  def destroy
    @danhmuc.destroy
    respond_to do |format|
      format.html { redirect_to admins_path, notice: "" }
      format.json { head :no_content }

     
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_danhmuc
      @danhmuc = Danhmuc.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def danhmuc_params
      params.require(:danhmuc).permit(:tendanhmuc)
    end
end

app/helpers/danhmucs_helper.rb
module DanhmucsHelper
end

app/views/danhmucs/_form.html.erb
<%= form_with(model: danhmuc) do |form| %>
  <% if danhmuc.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(danhmuc.errors.count, "error") %> prohibited this danhmuc from being saved:</h2>

      <ul>
        <% danhmuc.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :tendanhmuc,for:"exampleInputEmail1", class:"form-label" %>
    <%= form.text_field :tendanhmuc,class:"form-control",style:"width:700px" %>
  </div>

  <div class="actions">
    <%= form.submit class:"btn btn-primary" %>
  </div>
<% end %>

app/views/danhmucs/edit.html.erb
<style>
.full {
  background-image: url("/assets/bgm.jpg");
.form-control{
    color:white;
    width:500px;
}
}
</style>



<div class = "full" style="max-width:100%;height:800px;">
 <h1 style = "color:white;text-align:center">CẬP NHẬT DANH MỤC</h1>
 <div style="margin-left:450px;">
 
 <%= render 'form', danhmuc: @danhmuc %>

<%= link_to 'Show', @danhmuc %> |
<%= link_to 'Back', danhmucs_path %>


 </div>
 
</div>

app/views/danhmucs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Danhmucs</h1>

<table>
  <thead>
    <tr>
      <th>Tendanhmuc</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @danhmucs.each do |danhmuc| %>
      <tr>
        <td><%= danhmuc.tendanhmuc %></td>
        <td><%= link_to 'Show', danhmuc %></td>
        <td><%= link_to 'Edit', edit_danhmuc_path(danhmuc) %></td>
        <td><%= link_to 'Destroy', danhmuc, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Danhmuc', new_danhmuc_path %>

app/views/danhmucs/new.html.erb
<style>
.full {
  background-image: url("/assets/bgm.jpg");
.form-control{
    color:white;
    width:500px;
}
}
</style>



<div class = "full" style="max-width:100%;height:800px;">
 <h1 style = "color:white;text-align:center">THÊM DANH MỤC</h1>
 <div style="margin-left:450px;">
 
 
<%= render 'form', danhmuc: @danhmuc %>

<%= link_to 'Back', danhmucs_path %>

 </div>
 
</div>

app/views/danhmucs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tendanhmuc:</strong>
  <%= @danhmuc.tendanhmuc %>
</p>

<%= link_to 'Edit', edit_danhmuc_path(@danhmuc) %> |
<%= link_to 'Back', danhmucs_path %>